# Generated by Django 4.0.3 on 2022-04-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('aid', models.IntegerField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('source_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='connecting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(null=True)),
                ('application_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('source_url', models.TextField()),
            ],
        ),
    ]
